name: comment trigger
on:
  issue_comment:
    types: [created]
jobs:
  print-something:
    if: |
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, '/trigger')
    uses: ./.github/workflows/print_something.yml
    with:
      branch: ${GITHUB_REF}

  print-value:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF}
