name: Print Something
on:
  workflow_call:
    inputs:
      print-content:
        type: string

jobs:
  print-job:
    name: print payload to screen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.base_ref}}
      - run: echo ${{inputs.print-content}}
      - run: cat ./print_payload.txt
