name: Print Something
on: workflow_dispatch
jobs:
  print-job:
    name: print payload to screen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat ./print_payload.txt
